### ISSUE TITLE
New bug in edge costs

### ISSUE THREAD

**Issue by satrajit-chatterjee** [castacks/onr_meta#219]

**Comment by satrajit-chatterjee** [comment]
![Screenshot from 2021-12-07 15-34-22.png](https://images.zenhubusercontent.com/60ad42fad2c5ea521a754f0e/6368e868-6b9f-4860-b25a-f8b59d9d9a92)

pitch=1.03
    <arg name="budget" default="1000"/>
    <arg name="extend_dist" default="400"/>
    <arg name="extend_radius" default="20"/>
    <arg name="prune_radius" default="10"/>

**Comment by bradygm** [comment]
Didn't run it twice? Display issue? Not saving correct best path?
