### ISSUE TITLE
Define what type of memory sharing method we should use between updating the belief and using the belief within the planner.

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#292]

**Comment by andrewjong** [comment]
Nodelets are probably the way to go? https://robotics.stackexchange.com/a/19400

**Comment by andrewjong** [comment]
Talked with Lucas, Josh, and Andrew. They suggested to just try serializing and deserializing the object over ROS to see if it fits our needs.

**Comment by andrewjong** [comment]
Serializing and deserializing over ROS I think is the best for now. Even if we used Shared Memory, we'd still have to serialize and deserialize from shared memory. The amount of coding is probably similar, though more straightforward in ROS. Either way, it's a lot of serializing work.

**Comment by andrewjong** [comment]
https://docs.google.com/document/d/1Unw3prlV3N4wjBqjD2NaDAt6QQew973UkyHDA1oOi-M/edit
