### ISSUE TITLE
Polygon target prior messages are also geting added as target prior tracks.

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#350]

**Comment by andrewjong** [comment]
![image.png](https://images.zenhubusercontent.com/5d7fca0846611c000130d6b7/aab8bd94-4a67-46c8-828d-1b0b1cd545d8)

Fixed. This temporary workaround checks the TargetPrior's filtered_target to see that it's not all 0s. Ideally later we should factor out PolygonPrior and FilteredTargets to be separate entities.
