### ISSUE TITLE
Target propagation sampling bug

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#351]

**Comment by bradygm** [comment]
Many of the samples don't seem to make that much sense. They seem to be grouping in regions where there aren't even targets. How long the sim runs also seems to be affecting where they are sampled even though the particles haven't spread that much.

![image.png](https://images.zenhubusercontent.com/609755827efca0dff64a3751/bfe8fb47-8b8f-4d6c-b123-716fb928368a)

![image.png](https://images.zenhubusercontent.com/609755827efca0dff64a3751/296dc995-9f8f-4b6e-a575-8addbf9bbf3c)

**Comment by bradygm** [comment]
Here is another odd result

![image.png](https://images.zenhubusercontent.com/609755827efca0dff64a3751/cfbfc795-5752-4988-b47e-0f61f6fa4564)

**Comment by andrewjong** [comment]
In latest commit for me, seems to be working ![image.png](https://images.zenhubusercontent.com/5d7fca0846611c000130d6b7/c8c3904d-5f21-4e70-9d9c-76ac71d57bf4)

`catkin build && source devel/setup.zsh && roslaunch onr_tigris sim_belief_and_plan.launch rviz:=true search:=false track:=true`

**Comment by andrewjong** [comment]
This one also seems to work. 

`catkin build && source devel/setup.zsh && roslaunch onr_tigris sim_belief_and_plan.launch rviz:=true search:=true track:=true`

Perhaps fixing #355 fixed this
![image.png](https://images.zenhubusercontent.com/5d7fca0846611c000130d6b7/26d37b8a-e325-40a5-8078-ab16054ab262)
