### ISSUE TITLE
Run Sean's plan request that doesn't work and track down the issue.

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#432]

**Comment by andrewjong** [comment]
@bradygm is this still relevant? I'm not sure cuz I'm not on the email chain I think.

**Comment by bradygm** [comment]
@andrewjong Yeah, he sent me an email that after he runs multiple plan requests, it eventually fails. But then he was able to find that it was actually just one plan request. There is probably just a typo or something in it, but it could be an actual bug.
