### ISSUE TITLE
Trochoid Issues Notes (Broken down into subtasks now)

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#483]
Final length of path doesn't match the length returned by the leaf node.
- Full path is solved, then trimmed to extend distance. When solved again to the trimmed distance, the new path isn't the same as the old. 

JHU sees different final plans than us sometimes. 

Could finish the speed ups.

Also seems to add extra loops sometimes
100 mps track scenario 1 with greedy
![image.png](https://images.zenhubusercontent.com/609755827efca0dff64a3751/71f9bc4c-b723-462f-adc1-7985c8ebc7fd)
25 mps
![image.png](https://images.zenhubusercontent.com/609755827efca0dff64a3751/ce52fdc3-91ef-4398-a65d-2d3275db730e)

**Comment by bradygm** [comment]
Hey @sagars2 I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/informative-path-planning-projects-609755cde1765f00132eb1d4/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by andrewjong** [comment]
This is done now right?

**Comment by bradygm** [comment]
Nope
