### ISSUE TITLE
Simulated perception bug?

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#497]

**Comment by bradygm** [comment]
![image.png](https://images.zenhubusercontent.com/609755827efca0dff64a3751/34e0ddd3-b36a-40fb-a845-6fbd53e9df46)

The true state is not within the particle cloud

**Comment by andrewjong** [comment]
somewhat addressed with the new cov clipping. still seems to do poorly if the frustum sweeps quickly

**Comment by bradygm** [comment]
This is still a note in the ICRA post todos
