### ISSUE TITLE
Make TIGRIS work like before ICRA change

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#507]

**Comment by andrewjong** [comment]
Took a while bug figured it out. There had been a major bug in discretize_observations. See commit ec747319fe. This should also improve MCTS.

Here's TIGRIS working again

![image.png](https://images.zenhubusercontent.com/5d7fca0846611c000130d6b7/a09456ee-38aa-46c8-b65c-5731d98b3986)
