### ISSUE TITLE
Clean up SearchMap to use better data types. Remove all vector<vector<double>>

### ISSUE THREAD

**Issue by andrewjong** [castacks/onr_meta#528]
We have ROS poses, OMPL states, Eigen vectors, and `vector<vector<double>>`, all used to represent points in space. Ideally we should clean it up to just ROS poses and OMPL states.

**Comment by andrewjong** [comment]
👍

**Comment by bradygm** [comment]
@andrewjong I was cleaning up zenhub tasks and came accross this one again. When reading just the title, I thought it was about SearchMap, but is this task broader? When you say, "we should clean it up to just ROS poses and OMPL states", I don't think SearchMap even has the concept of states really. When I read the title I thought it was just about fixing the 2D vector of grid states.
