### ISSUE TITLE
Add analytical solution

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#537]

**Comment by sagars2** [comment]
Analytical Solution is outputting incorrect trajectories, however the test cases are passing. 2D plots are as below:![test_trochoids_analytical.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/7d22ef69-b051-4631-8c8f-58c486c5b22e)![test_trochoids_straight_analytical.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/7a398fe2-22a2-436f-af34-fb989c81d506)![test_trochoids.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/fb422d9a-a1b5-4895-987c-db5a9f296ee5)![trochoid_large_radius_analytical.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/9470fab6-803d-4a7a-8f49-c18f5d4a2de6)

**Comment by sagars2** [comment]
Wrote a visualization script which can visualize the csv's created after running the unit tests in 3D

**Comment by sagars2** [comment]
Update on analytical solutions:![Figure_1.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/692f8588-facd-46da-b6b9-85d97639cd14)![Figure_2.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/81e04368-af73-4630-a9d7-b0c5a9f7980a)![Figure_3.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/765a9bb4-6fbc-4a9b-b64e-a51e87597c3b)![Figure_4.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/ce8cfff0-31a9-48d0-ab40-d83c4f2095ed)![Figure_5.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/90f68088-756c-47d3-88be-de62a88f8a2b)![Figure_6.png](https://images.zenhubusercontent.com/6310d6ba2c7ea63918a4f426/dd45fdf1-4757-44f1-9697-8897c40b64c0)
