### ISSUE TITLE
Tree recycling- fix how the previous path is kept and indexed. Keeping too much each time.

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#688]

**Comment by andrewjong** [comment]
This is an important problem. Here's an example of keeping too much of the prior path:
![Screenshot from 2023-05-24 18-39-53.png](https://images.zenhubusercontent.com/5d7fca0846611c000130d6b7/de25f2fc-4eb5-47b3-9160-f7dbe296a3bb)
